name: tdlib
version: 0.3.0
github: "poscat0x04/tdlib"
license: BSD3
author: Poscat
maintainer: poscat@mail.poscat.moe
copyright: "(c) 2020 Poscat"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
synopsis: complete binding to the Telegram Database Library
category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/poscat0x04/tdlib#readme>

dependencies:
  - base >= 4.10 && < 5
  - bytestring
  - text
  - aeson >= 1.4.7
  - containers ^>= 0.6.2.1
  - unordered-containers ^>= 0.2.10.0
  - stm ^>= 2.5.0.0
  - polysemy >= 1.3.0.0
  - polysemy-plugin >= 0.2.5.0
  - monad-loops
  - tdlib-types ^>= 0.4.0

extra-libraries:
  - tdjson

ghc-options:
  - -fplugin=Polysemy.Plugin
  - -flate-specialise
  - -fspecialise-aggressively

default-extensions:
  - OverloadedStrings
  - FlexibleInstances
  - FlexibleContexts
  - FunctionalDependencies
  - InstanceSigs
  - ConstraintKinds
  - DeriveGeneric
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - TypeOperators
  - TypeApplications
  - TypeFamilies
  - KindSignatures
  - PartialTypeSignatures
  - DataKinds
  - StarIsType
  - ScopedTypeVariables
  - ExplicitForAll
  - ViewPatterns
  - BangPatterns
  - LambdaCase
  - TupleSections
  - EmptyCase
  - MultiWayIf
  - UnicodeSyntax
  - PatternSynonyms
  - RecordWildCards

library:
  source-dirs: src

tests:
  tdlib-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tdlib
      - base64-bytestring-type
      - QuickCheck
      - quickcheck-text
      - quickcheck-instances
